//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreParts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storepartsEntities : DbContext
    {
        public storepartsEntities()
            : base("name=storepartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<part> parts { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<waybill> waybills { get; set; }
    }
}
