//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace StoreParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdStore { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> TypePayOnline { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }

        [NotMapped]
        public double? SumOrder
        {
            get
            {
                double? sum = 0.0;
                foreach (var item in Parts)
                {
                    sum += item.RetailPrice;
                }
                return sum;
            }
        }


        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
    }
}
