//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public part()
        {
            this.waybills = new HashSet<waybill>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> id_brand { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public Nullable<int> retail_price { get; set; }
        public Nullable<int> wholesale_price { get; set; }
        public Nullable<int> count_storage { get; set; }
    
        public virtual brand brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waybill> waybills { get; set; }
    }
}
