//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreParts
{
    using System;
    using System.Collections.Generic;
    
    public partial class waybill
    {
        public int id_order { get; set; }
        public int id_part { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual part part { get; set; }
        public virtual order order { get; set; }
    }
}
